package com.scatterbrain.scatterfit.core

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Port of web scoring.test.ts + primitive cases. EVERY expected value below was
 * generated by running the TypeScript engine (scoring.ts / goals.ts) on this
 * machine — the Kotlin port must match it number-for-number.
 * Series tests pin todayKey — never real wall-clock.
 */
class ScoringTest {

    private val TODAY = "2026-10-06"

    private fun DailyData.withSteps(vararg d: Pair<String, Double>) = copy(steps = steps + d)
    private fun DailyData.withCal(vararg d: Pair<String, Double>) = copy(caloriesEaten = caloriesEaten + d)
    private fun DailyData.withRhr(vararg d: Pair<String, Double>) = copy(restingHr = restingHr + d)
    private fun DailyData.withDrinks(vararg d: Pair<String, Boolean>) = copy(drinks = drinks + d)
    private fun DailyData.withUnits(vararg d: Pair<String, Double>) = copy(alcoholUnits = alcoholUnits + d)

    private fun day(n: Int): String { // 22 Sep .. 06 Oct 2026, real rollover
        val d = java.time.LocalDate.of(2026, 9, 22).plusDays(n.toLong())
        return d.toString()
    }

    private fun calSeries(data: DailyData): GoalSeries =
        computeGoalSeries(data, ScoringSettings(), 7).first { it.id == GoalId.CALORIES }

    private fun rhrSeries(data: DailyData): GoalSeries =
        computeGoalSeries(data, ScoringSettings(), 1, TODAY).first { it.id == GoalId.RHR_TREND }

    // ---- partial calorie trap: the 500 kcal gate ----

    @Test fun `under 500 kcal logged = incomplete day - null never a perfect score`() {
        for (eaten in listOf(0.0, 120.0, 499.0)) {
            val s = calSeries(DailyData().withCal(TODAY to eaten)).days.last { it.day == TODAY }.score
            assertNull("eaten=$eaten", s)
        }
    }

    @Test fun `at or above 500 kcal scores normally against the kcal target`() {
        val target = 2270.0 // activeMacroTargets(DEFAULT) — kcal target on grams mode
        val s = calSeries(DailyData().withCal(TODAY to target)).days.last { it.day == TODAY }.score
        assertEquals(100.0, s!!, 1e-9)
    }

    @Test fun `missing day stays null`() {
        assertNull(calSeries(DailyData()).days.last { it.day == TODAY }.score)
    }

    @Test fun `boundary - exactly 500 scores 499 does not`() {
        val at = calSeries(DailyData().withCal(TODAY to 500.0)).days.last { it.day == TODAY }.score
        assertTrue(at != null && at <= 100.0)
        assertEquals(0.0, at!!, 1e-9)
        assertTrue(2270 > 500)
    }

    // ---- RHR swing: 10 bpm clamp window ----

    private fun rhrFixture(vals: Map<String, Double>): DailyData {
        var d = DailyData()
        for ((k, v) in vals) d = d.withRhr(k to v)
        return d
    }

    @Test fun `3 bpm swing no longer eats 40 pts - now about 15`() {
        val vals = (0 until 15).associate { day(it) to if (it < 8) 55.0 else 58.0 }
        assertEquals(35.0, rhrFixture(vals).let { rhrSeries(it).days.last().score }!!, 1e-9)
    }

    @Test fun `10 bpm is the full range - up and down`() {
        val up = (0 until 15).associate { day(it) to if (it < 8) 55.0 else 65.0 }
        val down = (0 until 15).associate { day(it) to if (it < 8) 55.0 else 45.0 }
        assertEquals(0.0, rhrSeries(rhrFixture(up)).days.last().score!!, 1e-9)
        assertEquals(100.0, rhrSeries(rhrFixture(down)).days.last().score!!, 1e-9)
    }

    @Test fun `flat stays neutral 50`() {
        val vals = (0 until 15).associate { day(it) to 55.0 }
        assertEquals(50.0, rhrSeries(rhrFixture(vals)).days.last().score!!, 1e-9)
    }

    @Test fun `3 bpm improvement is gentler too - 65 not 80`() {
        val vals = (0 until 15).associate { day(it) to if (it < 8) 58.0 else 55.0 }
        assertEquals(65.0, rhrSeries(rhrFixture(vals)).days.last().score!!, 1e-9)
    }

    @Test fun `short RHR history stays null`() {
        assertNull(rhrSeries(DailyData()).days.last().score)
    }

    // ---- score primitives (expected values generated from the TS engine) ----

    @Test fun `oneSidedScore`() {
        assertEquals(100.0, oneSidedScore(10000.0, 10000.0), 1e-9)
        assertEquals(50.0, oneSidedScore(5000.0, 10000.0), 1e-9)
        assertEquals(100.0, oneSidedScore(12000.0, 10000.0), 1e-9) // over-target clamps
        assertEquals(100.0, oneSidedScore(0.5, 0.0), 1e-9)          // zero target can't div-zero
    }

    @Test fun `twoSidedScore`() {
        assertEquals(100.0, twoSidedScore(2500.0, 2500.0), 1e-9)
        assertEquals(60.0, twoSidedScore(2750.0, 2500.0), 1e-9)     // 10% over = 60
        assertEquals(0.0, twoSidedScore(1000.0, 2500.0), 1e-9)      // far off clamps to 0
    }

    @Test fun `dailyPaceScore - reach mode projects`() {
        assertEquals(100.0, dailyPaceScore(6000.0, 10000.0, 0.5)!!, 1e-9)  // projects 12k
        assertEquals(90.0, dailyPaceScore(4500.0, 10000.0, 0.5)!!, 1e-9)   // projects 9k
    }

    @Test fun `dailyPaceScore - sparse morning stays neutral`() {
        assertNull(dailyPaceScore(1000.0, 10000.0, 0.25)) // 6am, under 75% of pace
    }

    @Test fun `dailyPaceScore - limit mode punishes overshoot`() {
        assertEquals(100.0, dailyPaceScore(800.0, 2500.0, 0.5, 0.0, PaceMode.LIMIT)!!, 1e-9)
        assertEquals(0.0, dailyPaceScore(3200.0, 2500.0, 0.5, 0.0, PaceMode.LIMIT)!!, 1e-9)
    }

    @Test fun `unitsScore - the continuous curve`() {
        assertEquals(100.0, unitsScore(0.0, 14.0), 1e-9)
        assertEquals(85.0, unitsScore(4.0, 14.0), 1e-9)
        assertEquals(74.5, unitsScore(7.0, 14.0), 1e-9)
        assertEquals(50.0, unitsScore(14.0, 14.0), 1e-9)   // exactly at target
        assertEquals(22.727272727272727, unitsScore(20.0, 14.0), 1e-9)
        assertEquals(0.0, unitsScore(25.0, 14.0), 1e-9)
    }

    @Test fun `progressTrendScore - trend vs pairwise SMA`() {
        assertEquals(0.0, progressTrendScore(78.5, 79.5, 80.0, 0.5, 0.2, 100.0)!!, 1e-9)
        assertEquals(100.0, progressTrendScore(79.5, 78.5, 80.0, 0.5, 0.2, 100.0)!!, 1e-9)
        assertEquals(100.0, progressTrendScore(79.9, 80.5, 80.0, 0.5, 0.2, 100.0)!!, 1e-9) // crossed
        assertNull(progressTrendScore(null, 79.5, 80.0, 0.5, 0.2, 100.0))
    }

    // ---- goal weights (worksheet block 10) ----

    @Test fun `effectiveWeights lifts soft targets to half the top`() {
        val eff = effectiveWeights(GoalPreset.FAT_LOSS)
        assertEquals(5.0, eff[GoalId.WEIGHT]!!, 1e-9)   // soft 0 -> half of bodyFat's 10
        assertEquals(10.0, eff[GoalId.BODY_FAT]!!, 1e-9)
        assertEquals(null, eff[GoalId.STEPS])           // unlisted stays unweighted
    }

    @Test fun `weightedDayScore - missing series never drags, soft never lifts`() {
        val eff = effectiveWeights(GoalPreset.FAT_LOSS)
        assertEquals(50.0, weightedDayScore(listOf(GoalId.STEPS to 80.0, GoalId.CALORIES to 50.0), eff)!!, 1e-9)
        assertEquals(50.0, weightedDayScore(listOf(GoalId.CALORIES to 50.0), eff)!!, 1e-9)
        assertEquals(50.0, weightedDayScore(listOf(GoalId.WEIGHT to 50.0), eff)!!, 1e-9)
        assertNull(weightedDayScore(emptyList(), eff))
    }

    @Test fun `goalVerdict words`() {
        assertEquals("no data yet", goalVerdict(null))
        assertEquals("off track", goalVerdict(30.0))
        assertEquals("needs work", goalVerdict(45.0))
        assertEquals("on track", goalVerdict(65.0))
        assertEquals("on track", goalVerdict(80.0))
    }

    // ---- momentum ----

    private fun mkSeries(vararg dayScores: List<Double?>): List<GoalSeries> {
        val ids = listOf(GoalId.STEPS, GoalId.CALORIES, GoalId.WEIGHT)
        return ids.mapIndexed { gi, id ->
            GoalSeries(id, id.name, dayScores[gi].mapIndexed { di, v -> GoalDay(day(14 + di), v) }, null, "")
        }
    }

    @Test fun `momentum plain average`() {
        val series = mkSeries(
            listOf(80.0, 60.0, null, 100.0, 90.0, 70.0, 50.0),
            listOf(100.0, 100.0, 100.0, null, null, 80.0, 60.0),
            listOf(null, null, null, null, null, null, 65.0),
        )
        val pts = computeMomentum(series, 7)
        assertEquals(90.0, pts[0].daily!!, 1e-9)
        assertEquals(80.0, pts[1].daily!!, 1e-9)
        assertEquals(100.0, pts[2].daily!!, 1e-9)
        assertEquals(75.0, pts[5].daily!!, 1e-9)
        assertEquals(58.333333333333336, pts[6].daily!!, 1e-9)
        // trailing 7-day rolling average (last three, as generated by the TS engine)
        assertEquals(92.0, pts[4].rolling!!, 1e-9)
        assertEquals(89.16666666666667, pts[5].rolling!!, 1e-9)
        assertEquals(84.76190476190477, pts[6].rolling!!, 1e-9)
    }

    @Test fun `momentum weighted by fat loss table`() {
        val series = mkSeries(
            listOf(80.0, 60.0, null, 100.0, 90.0, 70.0, 50.0),
            listOf(100.0, 100.0, 100.0, null, null, 80.0, 60.0),
            listOf(null, null, null, null, null, null, 65.0),
        )
        val pts = computeMomentum(series, 7, effectiveWeights(GoalPreset.FAT_LOSS))
        assertEquals(100.0, pts[0].daily!!, 1e-9)  // steps unweighted on fat loss
        assertNull(pts[3].daily)                   // only unweighted series scored
        assertEquals(80.0, pts[5].daily!!, 1e-9)
        assertEquals(61.92307692307692, pts[6].daily!!, 1e-9) // calories 8 + soft weight 5
    }

    // ---- colour spectrum ----

    @Test fun `scoreToColor endpoints and midpoint`() {
        assertEquals(0xFFF14D4C, scoreToColorArgb(0.0))
        assertEquals(0xFFF0BB3B, scoreToColorArgb(50.0))
        assertEquals(0xFF4FD57F, scoreToColorArgb(100.0))
        assertEquals(0xFF8A8A8A, scoreToColorArgb(null)) // muted, never a judgement colour
    }

    @Test fun `scoreToColor monotonic between stops`() {
        val a = scoreToColorArgb(10.0)
        val b = scoreToColorArgb(40.0)
        val c = scoreToColorArgb(90.0)
        assertFalse(a == b && b == c)
        assertTrue(scoreToColorArgb(49.0) != scoreToColorArgb(51.0))
    }
}
